apiVersion: v1
kind: ServiceAccount
metadata:
  name: diabetes-kserve-deployer
  namespace: diabet

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: diabetes-kserve-deployer
  namespace: diabet
rules:
  - apiGroups: ["serving.kserve.io"]
    resources: ["inferenceservices"]
    verbs: ["get", "list", "watch", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: diabetes-kserve-deployer
  namespace: diabet
subjects:
  - kind: ServiceAccount
    name: diabetes-kserve-deployer
    namespace: diabet
roleRef:
  kind: Role
  name: diabetes-kserve-deployer
  apiGroup: rbac.authorization.k8s.io
