apiVersion: batch/v1
kind: Job
metadata:
  name: diabetes-training-job
  namespace: diabet
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: diabetes-training
    spec:
      restartPolicy: Never
      containers:
        - name: diabetes-training
          image: serhatsdocker/diabetprediction-training
          imagePullPolicy: Always
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow-tracking.mlflow.svc.cluster.local"
          envFrom:
            - secretRef:
                name: mlflow-credentials
